---
# Source: webhook-helm-mini/templates/workload/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: webhookmini
  name: mini1-webhook-helm-mini-operator
spec:
  type: NodePort
  ports:
  # Port上的映射端口
  - port: 443
    targetPort: 443
    name: https
    nodePort: 30323
  selector:
    app: webhook-helm-mini-workload
