---
# Source: webhook-helm-mini/templates/admission-webhook/validatingWebhookConfiguration.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhook1-webhook-helm-mini-admission
  labels:
    app: webhook-helm-mini-admission
    helm.sh/chart: webhook-helm-mini-0.1.0
    app.kubernetes.io/name: webhook-helm-mini
    app.kubernetes.io/instance: webhook1
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
webhooks:
  - name: webhook1-webhook-helm-minirulemutate.mywebhook.com
    failurePolicy: Ignore
    rules:
      - apiGroups:
          - webhookmini.com
        apiVersions:
          - "*"
        resources:
          - prometheusrules
        operations:
          - CREATE
          - UPDATE
    clientConfig:
      service:
        namespace: mywebhook
        name: webhook1-webhook-helm-mini-operator
        path: /admission-prometheusrules/validate
    timeoutSeconds: 10
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
